spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  # ?????? ?? ??? ???? drop?? ?? ????.
    properties:
      hibernate:
        #      show_sql: true   # System.out? ?????? ?? SQL? ???.
        format_sql: true
logging.level:
  org.hibernate.SQL: debug  # logger? ?? ?????? ?? SQL? ???.

server:
  port: 8888

sns:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client:
      id: 132728480147-ctpsq5mg4eksbkc5d9u729ap67575j8l.apps.googleusercontent.com
      secret: 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
    callback:
      url: http://localhost:8888/auth/google/callback